### ISSUE TITLE
Support Swagger

### ISSUE THREAD

**Issue by yoonje** [SSU-NC/toiot#13]
The api documentation should provide swagger functionality independent of the notation in `README.md`.

- reference
https://dejavuqa.tistory.com/330

**Comment by KumKeeHyun** [comment]
thanks for information :)

**Comment by yoonje** [comment]
Good :)

**Comment by KumKeeHyun** [comment]
![image](https://user-images.githubusercontent.com/44857109/94274284-75794500-ff80-11ea-8394-d5788224ff7f.png)
done!
