### ISSUE TITLE
toiot feature implementation

### ISSUE THREAD

**Issue by KumKeeHyun** [SSU-NC/toiot#21]
Currently, `toiot` supports the ability to pass data generated by the sensor to the ELK responsible for visualization. Although it is a prototype version and not stable...

We talked about what features to implement in the PDK.
Considering the characteristics of our kafka and elk, PDK should supports a IoT service with a large scale and real time.

First, we investigated the structure and features of thingsboard, kaa, and AWS IoT, 
and as a result of consulting with the **professor**,
the features we basically need were:

1. Rule engine for data processing
    - Supporting additional operations on the data to make data analysis easier
    - Features supported by most IoT platforms
1. Authentication, security
1. Data analysis
1. Sensor grouping and management service for large-scale service

What do you think aboud this?

**Comment by yoonje** [comment]
These are enough. I think that authentication and security are hard. Firstly, focus basic features!
