### ISSUE TITLE
implement logic core

### ISSUE THREAD

**Issue by iamhge** [SSU-NC/toiot#31]
### base pipeline
* user input(logic) -> filter logic -> action

### logic
: user can add freely scope, select and action.
* select sensor
    * ex) sensor_1
* scope
    * ex) 10 <= value_1 <= 30
* select
    * ex) group
* action 
    * ex) email

### logic node
* timestamp
* location(group)
* value
* value's range

### action
* alarm
* email
* ...

Frontend send json & backend control logic input..
frontend have to create logic core UI.

**Comment by iamhge** [comment]
rule builder reference : https://ukrbublik.github.io/react-awesome-query-builder/

**Comment by iamhge** [comment]
* logic value, action(email, alarm) can exist 0~n.
* logic: "empty" fields are empty logic. These should be filtered.
    * ex)
```
{
    logic: 'empty',
    value: string,
    range: [{
        min: number,
        max: number
    }]
}
```

### POST request form
```
sensor_uuid: string;
logic: [
    {
        logic: "value",
        value: string,
        range: [{
            min: number,
            max: number
        }]
    },
    {
        logic: "time",
        range: [{
            start: string,
            end: string,
        }]
    },
    {
        logic: "group",
        group: [ string ]
    },
    {
        logic: string // alarm or email
        text: string
    }
]
````

**Comment by KumKeeHyun** [comment]
Thanks :)

**Comment by iamhge** [comment]
### Logic Core Table
1. frontend request logic core to back
2. backend send almost same msg ( which frontend send to backend ) to frontend
3. only #num added
4. empty elem should be filtered

**Comment by iamhge** [comment]
### web socket
We should implement web socket for alarm service.

**Comment by seheee** [comment]
### Logic Core API

- GET /logiccore
  -  get all logic core informations

- POST /logiccore
- DELETE /logiccore
  - delete logic core with id
  - `{"id":string}`

**Comment by KumKeeHyun** [comment]
TODO : support multiple logic-core process
maybe using event driven?
